apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-preprocessing-deployment
  labels:
    app: data-preprocessing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-preprocessing
  template:
    metadata:
      labels:
        app: data-preprocessing
    spec:
      containers:
      - name: data-preprocessing-container
        image: jeana0103/data_preprocessing_image:latest
        command: ["python", "data_preprocessing.py"]
        volumeMounts:
        - name: data-volume
          mountPath: /mnt/data  # This is where the datasets will be accessed
      restartPolicy: Always
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: shared-pvc
