apiVersion: v1
kind: Service
metadata:
  name: model-inference-service
spec:
  selector:
    app: model-inference
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000  # This should match the exposed port in your container
      nodePort: 30000   # NodePort exposed on your local machine (can be between 30000-32767), 
  type: NodePort  # This makes the service accessible on a port on your local machine
