apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-training-deployment
  labels:
    app: model-training
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-training
  template:
    metadata:
      labels:
        app: model-training
    spec:
      containers:
      - name: model-training-container
        image: jeana0103/model_training_image:latest
        command: ["python", "model_training.py"]
        volumeMounts:
        - name: data-volume
          mountPath: /mnt/data
      restartPolicy: Always
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: shared-pvc
