apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-pv
spec:
  capacity:
    storage: 10Gi  # Adjust storage as needed
  accessModes:
    - ReadWriteMany  # Allows multiple pods to read and write
  hostPath:
    path: /mnt/data  # Path on the host where the data is located
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi  # Must match the size of the PV
  storageClassName: standard  # Must match the storageClassName of the PV
